### ISSUE TITLE
ズームレベル5〜8での著作権表示

### ISSUE THREAD

**Issue by kasugaiasuka** [gsi-cyberjapan/gsitiles-openlayers3#2]
[標準地図](https://maps.gsi.go.jp/development/ichiran.html#std)および[淡色地図](https://maps.gsi.go.jp/development/ichiran.html#pale)では、ズームレベル5〜8の際、規定の地理院タイル一覧ページへのリンクだけではなく「The bathymetric contours are derived (後略)」の文章を追加するよう求められています。

こちらを文字通りに解釈すると

1. 地図のズームレベルの変更を検知する
1. ズームレベルに応じてsourceのattributionを動的に書き換える

のようなOpenLayersのクラスには用意されていない処理を別途追加する必要があるかと思うのですが、こちらのサンプルはないでしょうか？

**Comment by johofukyu** [comment]
ご提示の処理を行うサンプルコードはありません。
なお、標準地図及び淡色地図をズームレベル5～8で使用する場合、必ずしもズームレベルに応じてsourceのattributionを動的に書き換える必要はなく、ヘルプページなどに出所を明示していただければ結構です。

**Comment by kasugaiasuka** [comment]
ありがとうございます。別ページでの表示で対応いたします。
